### ISSUE TITLE
Nextjs reload slow

### ISSUE THREAD

**Issue by pvn2k1vn** [nvni/nextjs-docker-hotreload#1]
Nextjs có thể bị chậm khi reload

**Comment by pvn2k1vn** [comment]
Một số giải thích
https://stackoverflow.com/questions/30043872/docker-compose-node-modules-not-present-in-a-volume-after-npm-install-succeeds
https://forums.docker.com/t/why-does-the-node-modules-folder-requires-a-volume-in-order-to-be-present-in-the-container/109857

**Comment by npv2k1** [comment]
#58b1d149e541061898f465d0f89226d033fabe17

**Comment by npv2k1** [comment]
[https://github.com/nvni/nextjs-docker-hotreload/commit/58b1d149e541061898f465d0f89226d033fabe17](commit)
